version: "3"
services:
  db:
    container_name: furfree-db
    image: mariadb:10.4
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"

  telegram-bot:
    container_name: furfree-telegram-bot
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db
